parameters:
    sso.enabled: '%env(bool:ENABLE_SSO)%'
    app.file_units_gn: '%env(FILE_UNITS_GN)%'
    app.file_units_pn: '%env(FILE_UNITS_PN)%'
    app.file_jobs: '%env(FILE_JOBS)%'
    app.referentials_base_path: '%kernel.project_dir%/referentials'
    app.complaints_base_path: '%kernel.project_dir%/var/complaints'
    app.folder_rotation.count: '%env(FOLDER_ROTATION_COUNT)%'
    app.folder_rotation.treshold: '%env(FOLDER_ROTATION_TRESHOLD)%'
    app.oodrive.root_folder_id: '%env(OODRIVE_ROOT_FOLDER_ID)%'
    app.oodrive.fetched_folder_id: '%env(OODRIVE_FETCHED_FOLDER_ID)%'
    app.oodrive.tmp_complaint_folder: '%env(OODRIVE_TMP_COMPLAINT_FOLDER)%'
    complaint.processing_deadline: '%env(COMPLAINT_PROCESSING_DEADLINE)%'
    app.oodrive.declaration.cleanup.period: '%env(OODRIVE_DECLARATION_CLEANUP_PERIOD)%'
    app.oodrive.attachments.only.cleanup.period: '%env(OODRIVE_ATTACHMENTS_ONLY_CLEANUP_PERIOD)%'
    app.oodrive.report.cleanup.period: '%env(OODRIVE_REPORT_CLEANUP_PERIOD)%'
    app.oodrive.report.folder: '%env(OODRIVE_REPORT_FOLDER)%'
    app.oodrive.complaint.filename: '%env(OODRIVE_COMPLAINT_FILENAME)%'
    app.salesforce.id_domain: '%env(SALESFORCE_ID_DOMAIN)%'
    app.salesforce.auth_subdomain: '%env(SALESFORCE_AUTH_SUBDOMAIN)%'
    app.salesforce.rest_subdomain: '%env(SALESFORCE_REST_SUBDOMAIN)%'
    app.salesforce.domain: '%env(SALESFORCE_DOMAIN)%'
    app.salesforce.client_id: '%env(SALESFORCE_API_CLIENT_ID)%'
    app.salesforce.client_secret: '%env(SALESFORCE_API_CLIENT_SECRET)%'
    app.salesforce.recipient: '%env(SALESFORCE_RECIPIENT)%'
    app.citoyen.domain: '%env(CITOYEN_DOMAIN)%'
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            bool $ssoIsEnabled: '%sso.enabled%'
            $folderRotationCount: '%app.folder_rotation.count%'
            $folderRotationTreshold: '%app.folder_rotation.treshold%'
            $oodriveRootFolderId: '%app.oodrive.root_folder_id%'
            $oodriveFetchedFolderId: '%app.oodrive.fetched_folder_id%'
            $ppelConnection: '@doctrine.dbal.ppel_connection'
            $tmpComplaintFolderId: '%app.oodrive.tmp_complaint_folder%'
            $oodriveReportFolderName: '%app.oodrive.report.folder%'
            $oodriveComplaintFilename: '%app.oodrive.complaint.filename%'
            $salesForceClientId: '%app.salesforce.client_id%'
            $salesForceClientSecret: '%app.salesforce.client_secret%'
            $salesForceAuthDomain: 'https://%app.salesforce.id_domain%.%app.salesforce.auth_subdomain%.%app.salesforce.domain%'
            $salesForceRestDomain: 'https://%app.salesforce.id_domain%.%app.salesforce.rest_subdomain%.%app.salesforce.domain%'
            $salesForceRecipient: '%app.salesforce.recipient%'
            $citoyenDomain: '%app.citoyen.domain%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Referential\DataFixtures\Unit\UnitGNFileFixtures:
        arguments:
            $unitsGNFixturesPath: '%app.referentials_base_path%/%app.file_units_gn%'

    App\Referential\DataFixtures\Unit\UnitPNFileFixtures:
        arguments:
            $unitsPNFixturesPath: '%app.referentials_base_path%/%app.file_units_pn%'
            
    App\Referential\DataFixtures\Job\JobFileFixtures:
        arguments:
            $jobsFixturesPath: '%app.referentials_base_path%/%app.file_jobs%'

    App\Entity\Listener\ComplaintEntityListener:
        arguments:
            $complaintProcessingDeadline: '%complaint.processing_deadline%'
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Complaint' }
            - { name: 'doctrine.orm.entity_listener', event: 'postPersist', entity: 'App\Entity\Complaint' }

    Faker\Generator:
        factory: [ 'Faker\Factory', 'create' ]
        arguments: [ 'fr_FR' ]

    App\Oodrive\ApiClientInterface: '@App\Oodrive\ApiClient'

    # Oodrive HTTP Client Oauth management service
    App\Oodrive\OAuth2\GrantType\AuthorizationCodeGrantType:
        arguments:
            $tokenUrl: '%env(OODRIVE_BASE_URI)%/auth/oauth/token'
            $workspace: '%env(OODRIVE_WORKSPACE)%'
            $clientId: '%env(OODRIVE_OAUTH_CLIENT_ID)%'
            $clientSecret: '%env(OODRIVE_OAUTH_CLIENT_SECRET)%'
            $username: '%env(OODRIVE_USERNAME)%'
            $password: '%env(OODRIVE_PASSWORD)%'

    App\Complaint\Messenger\ComplaintFetch\ComplaintFetchHandler:
        arguments:
            $complaintsBasePath: '%app.complaints_base_path%'

    App\Complaint\Parser\FileParser:
        arguments:
            $complaintsBasePath: '%app.complaints_base_path%'
            
    App\Repository\ComplaintRepository:
        arguments:
            $oodriveDeclarationCleanUpPeriod: '%app.oodrive.declaration.cleanup.period%'
            $oodriveAttachmentsOnlyCleanUpPeriod: '%app.oodrive.attachments.only.cleanup.period%'
            $oodriveReportCleanUpPeriod: '%app.oodrive.report.cleanup.period%'       

    app.logger.formatter.json_traces:
        class: App\Logger\Formatter\ApplicationTracesFormatter

    Aws\S3\S3Client:
        arguments:
            -   
                version: '2006-03-01'
                region: '%env(AWS_S3_REGION)%'
                endpoint: '%env(AWS_S3_ENDPOINT)%'
                use_path_style_endpoint: True
                public: True
                credentials:
                    key: '%env(AWS_S3_ACCESS_ID)%'
                    secret: '%env(AWS_S3_ACCESS_SECRET)%'
