parameters:
    sso.enabled: '%env(bool:ENABLE_SSO)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            bool $ssoIsEnabled: '%sso.enabled%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
