services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Oodrive\ApiClientInterface: '@App\Tests\Behat\MockedClasses\FakeOodriveApiClient'
    
    App\Complaint\Parser\CorporationParser:
        public: true

    App\Complaint\Parser\FactsParser:
        public: true

    App\Complaint\Parser\AdditionalInformationParser:
        public: true

    App\Complaint\Parser\FileParser:
        public: true`
        arguments:
            $complaintsBasePath: '%app.complaints_base_path%'
