parameters:
    sso.enabled: '%env(bool:ENABLE_SSO)%'
    app.file_units_gn: '%env(FILE_UNITS_GN)%'
    app.file_units_pn: '%env(FILE_UNITS_PN)%'
    app.file_services: '%env(FILE_SERVICES)%'
    app.referentials_base_path: '%kernel.project_dir%/referentials'
    app.complaints_base_path: '%kernel.project_dir%/var/complaints'
    app.folder_rotation.count: '%env(FOLDER_ROTATION_COUNT)%'
    app.folder_rotation.treshold: '%env(FOLDER_ROTATION_TRESHOLD)%'
    app.oodrive.root_folder_id: '%env(OODRIVE_ROOT_FOLDER_ID)%'
    app.oodrive.fetched_folder_id: '%env(OODRIVE_FETCHED_FOLDER_ID)%'
    complaint.processing_deadline: '%env(COMPLAINT_PROCESSING_DEADLINE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            bool $ssoIsEnabled: '%sso.enabled%'
            $folderRotationCount: '%app.folder_rotation.count%'
            $folderRotationTreshold: '%app.folder_rotation.treshold%'
            $oodriveRootFolderId: '%app.oodrive.root_folder_id%'
            $oodriveFetchedFolderId: '%app.oodrive.fetched_folder_id%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Referential\DataFixtures\Service\ServiceFileFixtures:
        arguments:
            $servicesFixturesPath: '%app.referentials_base_path%/%app.file_services%'
    
    App\Referential\DataFixtures\Unit\UnitGNFileFixtures:
        arguments:
            $unitsGNFixturesPath: '%app.referentials_base_path%/%app.file_units_gn%'

    App\Referential\DataFixtures\Unit\UnitPNFileFixtures:
        arguments:
            $unitsPNFixturesPath: '%app.referentials_base_path%/%app.file_units_pn%'

    App\Entity\Listener\ComplaintEntityListener:
        arguments:
            $complaintProcessingDeadline: '%complaint.processing_deadline%'
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Complaint' }
            - { name: 'doctrine.orm.entity_listener', event: 'postPersist', entity: 'App\Entity\Complaint' }

    Faker\Generator:
        factory: [ 'Faker\Factory', 'create' ]
        arguments: [ 'fr_FR' ]

    App\Oodrive\ApiClientInterface: '@App\Oodrive\ApiClient'

    # Oodrive HTTP Client Oauth management service
    App\Oodrive\OAuth2\GrantType\AuthorizationCodeGrantType:
        arguments:
            $tokenUrl: '%env(OODRIVE_BASE_URI)%/auth/oauth/token'
            $workspace: '%env(OODRIVE_WORKSPACE)%'
            $clientId: '%env(OODRIVE_OAUTH_CLIENT_ID)%'
            $clientSecret: '%env(OODRIVE_OAUTH_CLIENT_SECRET)%'
            $username: '%env(OODRIVE_USERNAME)%'
            $password: '%env(OODRIVE_PASSWORD)%'

    App\Report\SendReportHandler:
        arguments:
            $tmpComplaintFolderId: '%env(OODRIVE_TMP_COMPLAINT_FOLDER)%'

    App\Messenger\ComplaintFetch\ComplaintFetchHandler:
        arguments:
            $complaintsBasePath: '%app.complaints_base_path%'

    App\Complaint\Parser\FileParser:
        arguments:
            $complaintsBasePath: '%app.complaints_base_path%'
