parameters:
    sso.enabled: '%env(bool:ENABLE_SSO)%'
    app.file_units: '%env(FILE_UNITS)%'
    app.referentials_base_path: '%kernel.project_dir%/referentials'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            bool $ssoIsEnabled: '%sso.enabled%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Referential\DataFixtures\Unit\UnitFileFixtures:
        arguments:
            $unitsFixturesPath: '%app.referentials_base_path%/%app.file_units%'
