imports:
    - { resource: services_test_common.yaml }
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            bool $ssoIsEnabled: '%sso.enabled%'

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
