variables:
    HARBOR_PROJECT: "ministere-de-linterieur-plaintes-en-ligne-pel-2"
    PHP_AGENT_ARTIFACT_NAME: "php-agent:$CI_COMMIT_REF_SLUG"
    PHP_CITOYEN_ARTIFACT_NAME: "php-citoyen:$CI_COMMIT_REF_SLUG"
    PHP_AGENT_CHANGE: 0
    PHP_CITOYEN_CHANGE: 0
    KUBERNETES_MEMORY_REQUEST: 1Gi
    KUBERNETES_MEMORY_LIMIT: 1Gi

workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_TAG
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_BRANCH == "main"

stages:
    - check
    - build
    - security
    - quality
    - test

#######################################
##         Basic Inheritance         ##
#######################################

.basic-override: &basic-override
    dependencies: []
    tags:
        - docker
        - rancher

.agent-step: &agent-step
    image: "registry.smile.fr/${HARBOR_PROJECT}/${PHP_AGENT_ARTIFACT_NAME}"
    before_script:
        - cd ./portail_agent/
    <<: *basic-override

.frontend-step: &frontend-step
    image: node:16
    <<: *basic-override

.citoyen-frontend-step: &citoyen-frontend-step
    <<: *frontend-step
    before_script:
        - cd ./portail_citoyen/

.agent-frontend-step: &agent-frontend-step
    <<: *frontend-step
    before_script:
        - cd ./portail_agent/

.citoyen-step: &citoyen-step
    image: "registry.smile.fr/${HARBOR_PROJECT}/${PHP_CITOYEN_ARTIFACT_NAME}"
    before_script:
        - cd ./portail_citoyen/
    <<: *basic-override

#######################################
##       Caches configurations       ##
#######################################

.cache-tools-agent: &cache-tools-agent
    cache:
        key: tools-agent-$CI_COMMIT_REF_SLUG
        paths:
            - "portail_agent/tools"

.cache-tools-citoyen: &cache-tools-citoyen
    cache:
        key: tools-citoyen-$CI_COMMIT_REF_SLUG
        paths:
            - "portail_citoyen/tools"

.cache-vendor-agent: &cache-vendor-agent
    cache:
        key: vendor-agent-$CI_COMMIT_REF_SLUG
        paths:
            - "portail_agent/vendor"

.cache-vendor-citoyen: &cache-vendor-citoyen
    cache:
        key: vendor-citoyen-$CI_COMMIT_REF_SLUG
        paths:
            - "portail_citoyen/vendor"

.cache-front-agent: &cache-front-agent
    cache:
        key: front-agent-$CI_COMMIT_REF_SLUG
        paths:
            - "portail_agent/public"
            - "portail_agent/node_modules"

.cache-front-citoyen: &cache-front-citoyen
    cache:
        key: front-citoyen-$CI_COMMIT_REF_SLUG
        paths:
            - "portail_citoyen/public"
            - "portail_citoyen/node_modules"

.cache-complete-agent: &cache-complete-agent
    cache:
        - key: front-agent-$CI_COMMIT_REF_SLUG
          paths:
              - "portail_agent/public"
              - "portail_agent/node_modules"
        - key: vendor-agent-$CI_COMMIT_REF_SLUG
          paths:
              - "portail_agent/vendor"

.cache-complete-citoyen: &cache-complete-citoyen
    cache:
        - key: front-citoyen-$CI_COMMIT_REF_SLUG
          paths:
              - "portail_citoyen/public"
              - "portail_citoyen/node_modules"
        - key: vendor-citoyen-$CI_COMMIT_REF_SLUG
          paths:
              - "portail_citoyen/vendor"

#######################################
##               Check               ##
#######################################

check-php-agent-change:
    stage: check
    image: docker
    script:
        - echo 'PHP_AGENT_CHANGE=1' >> build.env
    <<: *basic-override
    artifacts:
        reports:
            dotenv: build.env
    only:
        changes:
            - docker-compose.yml
            - ./portail_agent/Dockerfile
            - ./portail_agent/docker/**/*

check-php-citoyen-change:
    stage: check
    image: docker
    script:
        - echo 'PHP_CITOYEN_CHANGE=1' >> build.env
    only:
        changes:
            - docker-compose.yml
            - ./portail_citoyen/Dockerfile
            - ./portail_citoyen/docker/**/*
    <<: *basic-override
    artifacts:
        reports:
            dotenv: build.env

check-php-images:
    stage: check
    image: docker
    variables:
        PHP_AGENT_CHANGE: 0
        PHP_CITOYEN_CHANGE: 0
    script:
        - echo "${HARBOR_PASSWORD}" | docker login registry.smile.fr -u ${HARBOR_USER} --password-stdin
        - docker manifest inspect registry.smile.fr/${HARBOR_PROJECT}/${PHP_AGENT_ARTIFACT_NAME} && echo 'PHP_AGENT_EXIST=1' >> build.env || echo 'PHP_AGENT_EXIST=0' >> build.env && true
        - docker manifest inspect registry.smile.fr/${HARBOR_PROJECT}/${PHP_CITOYEN_ARTIFACT_NAME} && echo 'PHP_CITOYEN_EXIST=1' >> build.env || echo 'PHP_CITOYEN_EXIST=0' >> build.env && true
    <<: *basic-override
    artifacts:
        reports:
            dotenv: build.env
    dependencies:
        - check-php-agent-change
        - check-php-citoyen-change

#######################################
##               Build               ##
#######################################

agent-build-php:
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    stage: build
    variables:
        PHP_AGENT_CHANGE: 0
        PHP_AGENT_EXIST: 0
    script:
        - echo "PHP_AGENT_CHANGE=${PHP_AGENT_CHANGE}"
        - echo "PHP_AGENT_EXIST=${PHP_AGENT_EXIST}"
        - mkdir -p /kaniko/.docker
        - |
            cat > /kaniko/.docker/config.json <<EOM
            {
                "auths": {
                    "registry.smile.fr": {
                        "auth": "$(printf "%s:%s" "${HARBOR_USER}" "${HARBOR_PASSWORD}" | base64 | tr -d '\n')"
                    }
                }
            }
            EOM
        - |
            if [ ${PHP_AGENT_CHANGE} -eq 1 ] || [ ${PHP_AGENT_EXIST} -eq 0 ];
            then
                echo "Build of PHP Agent needed"

                /kaniko/executor --context "${CI_PROJECT_DIR}/portail_agent/" --build-arg "BUILD_PATH='./portail_agent/'" --target "symfony_php" --destination "registry.smile.fr/${HARBOR_PROJECT}/${PHP_AGENT_ARTIFACT_NAME}"
            else
                echo "Build of PHP Agent not needed"
            fi
    <<: *basic-override
    dependencies:
        - check-php-images

citoyen-build-php:
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    stage: build
    variables:
        PHP_CITOYEN_CHANGE: 0
        PHP_CITOYEN_EXIST: 0
    script:
        - echo "PHP_CITOYEN_CHANGE=${PHP_CITOYEN_CHANGE}"
        - echo "PHP_CITOYEN_EXIST=${PHP_CITOYEN_EXIST}"
        - mkdir -p /kaniko/.docker
        - |
            cat > /kaniko/.docker/config.json <<EOM
            {
                "auths": {
                    "registry.smile.fr": {
                        "auth": "$(printf "%s:%s" "${HARBOR_USER}" "${HARBOR_PASSWORD}" | base64 | tr -d '\n')"
                    }
                }
            }
            EOM
        - >-
            if [ ${PHP_CITOYEN_CHANGE} -eq 1 ] || [ ${PHP_CITOYEN_EXIST} -eq 0 ];
            then
                echo "Build of PHP Citoyen needed"
                /kaniko/executor --context "${CI_PROJECT_DIR}/portail_citoyen/" --build-arg "BUILD_PATH='./portail_citoyen/'" --target "symfony_php" --destination "registry.smile.fr/${HARBOR_PROJECT}/${PHP_CITOYEN_ARTIFACT_NAME}"
            else
                echo "Build of PHP Citoyen not needed"
            fi
    <<: *basic-override
    dependencies:
        - check-php-images

.build-tools: &build-tools
    stage: build
    script:
        - make tools-install

agent-build-tools:
    <<: *agent-step
    <<: *cache-tools-agent
    <<: *build-tools
    needs:
        - agent-build-php

citoyen-build-tools:
    <<: *citoyen-step
    <<: *cache-tools-citoyen
    <<: *build-tools
    needs:
        - citoyen-build-php

.build-vendor: &build-vendor
    stage: build
    script:
        - make vendor

agent-build-vendor:
    <<: *agent-step
    <<: *cache-vendor-agent
    <<: *build-vendor
    needs:
        - agent-build-php

citoyen-build-vendor:
    <<: *citoyen-step
    <<: *cache-vendor-citoyen
    <<: *build-vendor
    needs:
        - citoyen-build-php

.build-front: &build-front
    stage: build
    script:
        - make install
        - make build-ci

agent-build-front:
    <<: *cache-complete-agent
    <<: *build-front
    <<: *agent-frontend-step
    <<: *basic-override
    needs:
        - agent-build-vendor

citoyen-build-front:
    <<: *cache-complete-citoyen
    <<: *build-front
    <<: *basic-override
    <<: *citoyen-frontend-step
    variables:
        KUBERNETES_MEMORY_REQUEST: 1Gi
        KUBERNETES_MEMORY_LIMIT: 1Gi
    needs:
        - citoyen-build-vendor

#######################################
##            Quality Tools           #
#######################################

## Security ##
.symfony-security: &symfony-security
    stage: security
    script:
        - make security

agent-symfony-security:
    <<: *agent-step
    <<: *symfony-security

citoyen-symfony-security:
    <<: *citoyen-step
    <<: *symfony-security

.frontend-audit: &frontend-audit
    stage: security
    script:
        - make frontend-audit

citoyen-frontend-security:
    <<: *cache-complete-citoyen
    <<: *frontend-audit
    <<: *citoyen-frontend-step

## Php Cs Fixer ##
.cs: &cs
    stage: quality
    script:
        - make cs

agent-php-cs:
    <<: *cache-tools-agent
    <<: *agent-step
    <<: *cs

citoyen-php-cs:
    <<: *cache-tools-citoyen
    <<: *citoyen-step
    <<: *cs

.frontend-twig-cs: &frontend-twig-cs
    stage: quality
    script:
        - make frontend-twig-cs-test

citoyen-frontend-twig-cs:
    <<: *citoyen-step
    <<: *cache-complete-citoyen
    <<: *frontend-twig-cs

.frontend-cs: &frontend-cs
    stage: quality
    script:
        - make frontend-cs-test

citoyen-frontend-cs:
    <<: *citoyen-frontend-step
    <<: *cache-complete-citoyen
    <<: *frontend-cs

.frontend-cpd: &frontend-cpd
    stage: quality
    script:
        - make frontend-cpd-test

citoyen-frontend-cpd:
    <<: *citoyen-frontend-step
    <<: *cache-complete-citoyen
    <<: *frontend-cpd

## Php Magic Number Detector ##
.mnd: &mnd
    stage: quality
    script:
        - make mnd

agent-php-mnd:
    <<: *cache-tools-agent
    <<: *agent-step
    <<: *mnd

citoyen-php-mnd:
    <<: *cache-tools-citoyen
    <<: *citoyen-step
    <<: *mnd

## Phpstan ##
.phpstan: &phpstan
    stage: quality
    script:
        - make phpstan

agent-php-phpstan:
    <<: *agent-step
    <<: *phpstan
    cache:
        - key: tools-agent-$CI_COMMIT_REF_SLUG
          paths:
              - "portail_agent/tools"
        - key: vendor-agent-$CI_COMMIT_REF_SLUG
          paths:
              - "portail_agent/vendor"

citoyen-php-phpstan:
    <<: *citoyen-step
    <<: *phpstan
    cache:
        - key: tools-citoyen-$CI_COMMIT_REF_SLUG
          paths:
              - "portail_citoyen/tools"
        - key: vendor-citoyen-$CI_COMMIT_REF_SLUG
          paths:
              - "portail_citoyen/vendor"

## Php Assumption ##
.assumption: &assumption
    stage: quality
    script:
        - make assumption

agent-php-assumption:
    <<: *cache-tools-agent
    <<: *agent-step
    <<: *assumption

citoyen-php-assumption:
    <<: *cache-tools-citoyen
    <<: *citoyen-step
    <<: *assumption

## Php Copy/Past Detector ##
.cpd: &cpd
    stage: quality
    script:
        - make cpd

agent-php-cpd:
    <<: *cache-tools-agent
    <<: *agent-step
    <<: *cpd

citoyen-php-cpd:
    <<: *cache-tools-citoyen
    <<: *citoyen-step
    <<: *cpd

#######################################
##          Tests Frameworks          #
#######################################

## PhpUnit ##
.unit: &unit
    stage: test
    script:
        - make unit

agent-unit:
    <<: *cache-vendor-agent
    <<: *agent-step
    <<: *unit

citoyen-unit:
    <<: *cache-vendor-citoyen
    <<: *citoyen-step
    <<: *unit

## Behat ##
.func: &func
    stage: test
    script:
        - make behat

agent-func:
    <<: *cache-complete-agent
    <<: *agent-step
    <<: *func
    variables:
        APP_ENV: "test"
        POSTGRES_DB: "app_test"
        POSTGRES_PASSWORD: "ChangeMe"
        POSTGRES_USER: "symfony"
    script:
        - make APP_ENV=${APP_ENV} db-ci-setup
        - make APP_ENV=${APP_ENV} db-load
        - make behat
    services:
        - name: postgres:13-alpine
          alias: database-func-agent

citoyen-func:
    <<: *cache-complete-citoyen
    <<: *citoyen-step
    <<: *func
    variables:
        APP_ENV: "test"
        POSTGRES_DB: "app_test"
        POSTGRES_PASSWORD: "ChangeMe"
        POSTGRES_USER: "symfony"
    script:
        - make APP_ENV=${APP_ENV} db-ci-setup
        - make APP_ENV=${APP_ENV} referential-create
        - make APP_ENV=${APP_ENV} referential-load
        - make behat
    services:
        - name: postgres:13-alpine
          alias: database-func-citoyen

citoyen-e2e:
    <<: *cache-complete-citoyen
    <<: *citoyen-step
    variables:
        APP_ENV: "e2e"
        POSTGRES_DB: "app"
        POSTGRES_PASSWORD: "ChangeMe"
        POSTGRES_USER: "symfony"
    script:
        - php bin/console cache:clear --env=${APP_ENV}
        - echo "APP_ENV=${APP_ENV}" >> .env.local
        - php -S 127.0.0.1:8080 -t public/ > /dev/null 2>&1 &
        - sed -i "s/nginx-citoyen/127.0.0.1:8080/g" behat.yml.dist
        - make APP_ENV=${APP_ENV} db-ci-setup
        - make APP_ENV=${APP_ENV} referential-create
        - make APP_ENV=${APP_ENV} referential-load
        - make e2e
    artifacts:
        name: "citoyen-e2e-$CI_COMMIT_REF_NAME"
        paths:
            - /builds/ministere-de-l-interieur/plaintes-en-ligne-pel/portail_citoyen/var/log
            - /builds/ministere-de-l-interieur/plaintes-en-ligne-pel/portail_citoyen/build/screenshots
        expire_in: 1 week
        when: on_failure
    services:
        - name: postgres:13-alpine
          alias: database-e2e-citoyen
        - name: selenium/standalone-chrome:4.5.3
          alias: chrome
        - name: redislabs/rejson:latest
          alias: redis-citoyen
    allow_failure: true

agent-e2e:
    <<: *cache-complete-agent
    <<: *agent-step
    variables:
        APP_ENV: "prod"
        POSTGRES_DB: "app"
        POSTGRES_PASSWORD: "ChangeMe"
        POSTGRES_USER: "symfony"
    script:
        - php bin/console cache:clear --env=e2e
        - APP_ENV=e2e php -S 127.0.0.1:8080 -t public/ > /dev/null 2>&1 &
        - sed -i "s/nginx-agent/127.0.0.1:8080/g" behat.yml.dist
        - make e2e
    services:
        - name: postgres:13-alpine
          alias: database-e2e-agent
        - name: selenium/standalone-chrome
          alias: chrome
    artifacts:
        name: "agent-e2e-$CI_COMMIT_REF_NAME"
        paths:
            - /builds/ministere-de-l-interieur/plaintes-en-ligne-pel/portail_agent/var/log
            - /builds/ministere-de-l-interieur/plaintes-en-ligne-pel/portail_agent/build/screenshots
        expire_in: 1 week
        when: on_failure
    allow_failure: true
