version: '3.4'

services:
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=

  php-citoyen:
    environment:
      APP_ENV: e2e
