version: '3.4'

services:
  activemq:
    image: symptoma/activemq:5.18.0
    environment:
        ACTIVEMQ_WEBADMIN_USERNAME: admin
        ACTIVEMQ_WEBADMIN_PASSWORD: admin
        ACTIVEMQ_USERNAME: system
        ACTIVEMQ_PASSWORD: manager
        
  minio:
    image: minio/minio
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: superadmin
      MINIO_ROOT_PASSWORD: superadmin
      MINIO_REGION_NAME: eu-west-3 
    entrypoint: sh
    command: -c 'mkdir -p /data/pel-bucket && minio server --console-address 0.0.0.0:9001 /data'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: '30s'
      timeout: '20s'
      retries: 3
    restart: 'unless-stopped'
    
  php-citoyen:
    build:
      context: ./portail_citoyen
      target: symfony_php
      args:
        PHP_VERSION: 8.1
        SYMFONY_VERSION: 6.1.*
        SKELETON: symfony/skeleton
        STABILITY: stable
        BUILD_PATH: ./portail_citoyen/
    restart: unless-stopped
    depends_on:
      - database-citoyen
      - redis-citoyen
    volumes:
      - citoyen-public:/srv/citoyen/public:rw
      - ./portail_citoyen/public/index.php:/srv/citoyen/public/index.php:ro
      - ./portail_citoyen/public/robots.txt:/srv/citoyen/public/robots.txt:ro
      - ./portail_citoyen/var:/srv/citoyen/var
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      REFERENTIALS_DATABASE_URL: postgresql://${POSTGRES_REFERENTIAL_USER:-symfony}:${POSTGRES_REFERENTIAL_PASSWORD:-ChangeMe}@database-citoyen:5432/${POSTGRES_REFERENTIAL_DB:-reference}?serverVersion=${POSTGRES_REFERENTIAL_VERSION:-13}

  php-agent:
    build:
      context: ./portail_agent
      target: symfony_php
      args:
        PHP_VERSION: 8.1
        SYMFONY_VERSION: 6.2.*
        SKELETON: symfony/skeleton
        STABILITY: stable
        BUILD_PATH: ./portail_agent/
    restart: unless-stopped
    depends_on:
      - database-agent
      - database-ppel
    volumes:
      - agent-public:/srv/agent/public:ro
      - ./portail_agent/var:/srv/agent/var
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_AGENT_USER:-symfony}:${POSTGRES_AGENT_PASSWORD:-ChangeMe}@database-agent:5432/${POSTGRES_AGENT_DB:-app}?serverVersion=${POSTGRES_AGENT_VERSION:-13}
      REFERENTIALS_DATABASE_URL: postgresql://${POSTGRES_REFERENTIAL_USER:-symfony}:${POSTGRES_REFERENTIAL_PASSWORD:-ChangeMe}@database-agent:5432/${POSTGRES_REFERENTIAL_DB:-reference}?serverVersion=${POSTGRES_REFERENTIAL_VERSION:-13}
      PPEL_DATABASE_URL: mysql://${PPEL_USER:-ppel}:${PPEL_PASSWORD:-ppel}@database-ppel:3306/${PPEL_DB:-plainteinternet}?serverVersion=${PPEL_VERSION:-5.7.33}
  
  nginx-citoyen:
    image: nginx
    depends_on:
      - php-citoyen
    restart: unless-stopped
    volumes:
      - citoyen-public:/srv/citoyen/public:rw
      - ./portail_citoyen/public/robots.txt:/srv/citoyen/public/robots.txt:ro

  nginx-agent:
    image: nginx
    depends_on:
      - php-agent
    restart: unless-stopped
    volumes:
      - agent-public:/srv/agent/public:ro

  node-citoyen:
    image: node:16
    tty: true
    volumes:
      - ./portail_citoyen:/srv/citoyen
      - citoyen-public:/srv/citoyen/public:rw
    working_dir: /srv/citoyen

  node-agent:
    image: node:16
    tty: true
    volumes:
      - ./portail_agent:/srv/agent
      - agent-public:/srv/agent/public:rw
    working_dir: /srv/agent

  database-agent:
    image: postgres:${POSTGRES_AGENT_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_AGENT_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_AGENT_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_AGENT_USER:-symfony}
    volumes:
      - db-data-agent:/var/lib/postgresql/data:rw

  database-citoyen:
    image: postgres:${POSTGRES_CITOYEN_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_CITOYEN_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_CITOYEN_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_CITOYEN_USER:-symfony}
    volumes:
      - db-data-citoyen:/var/lib/postgresql/data:rw

  database-ppel:
    image: mysql:5.7.33
    environment:
      MYSQL_DATABASE: plainteinternet
      MYSQL_USER: ppel
      MYSQL_PASSWORD: ppel
      MYSQL_ROOT_PASSWORD: ppel
    ports:
      - "9906:3306"
    volumes:
        - ./docker/ppel:/docker-entrypoint-initdb.d
        - db-ppel:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=latin1', '--collation-server=latin1_swedish_ci' ]
  
  ###< doctrine/doctrine-bundle ###

  redis-citoyen:
    image: redislabs/rejson:latest

volumes:
  minio:
  citoyen-public:
  agent-public:
  ###> doctrine/doctrine-bundle ###
  db-data-agent:
  db-data-citoyen:
  ###< doctrine/doctrine-bundle ###
  db-ppel:
