version: '3.4'

services:
  php-citoyen:
    build:
      context: ./portail_citoyen
      target: symfony_php
      args:
        PHP_VERSION: 8.1
        SYMFONY_VERSION: 6.1.*
        SKELETON: symfony/skeleton
        STABILITY: stable
        BUILD_PATH: ./portail_citoyen/
    restart: unless-stopped
    depends_on:
      - database-citoyen
      - redis-citoyen
    volumes:
      - citoyen-public:/srv/citoyen/public:rw
      - ./portail_citoyen/public/robots.txt:/srv/citoyen/public/robots.txt:ro
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-symfony}:${POSTGRES_PASSWORD:-ChangeMe}@database-citoyen:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-13}

  php-agent:
    build:
      context: ./portail_agent
      target: symfony_php
      args:
        PHP_VERSION: 8.1
        SYMFONY_VERSION: 6.2.*
        SKELETON: symfony/skeleton
        STABILITY: stable
        BUILD_PATH: ./portail_citoyen/
    restart: unless-stopped
    depends_on:
      - database-agent
    volumes:
      - agent-public:/srv/agent/public:ro
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-symfony}:${POSTGRES_PASSWORD:-ChangeMe}@database-agent:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-13}

  nginx-citoyen:
    image: nginx
    depends_on:
      - php-citoyen
    restart: unless-stopped
    volumes:
      - citoyen-public:/srv/citoyen/public:rw
      - ./portail_citoyen/public/robots.txt:/srv/citoyen/public/robots.txt:ro

  nginx-agent:
    image: nginx
    depends_on:
      - php-agent
    restart: unless-stopped
    volumes:
      - agent-public:/srv/agent/public:ro

  node-citoyen:
    image: node:16
    tty: true
    volumes:
      - ./portail_citoyen:/srv/citoyen
      - citoyen-public:/srv/citoyen/public:rw
    working_dir: /srv/citoyen

  node-agent:
    image: node:16
    tty: true
    volumes:
      - ./portail_agent:/srv/agent
      - agent-public:/srv/agent/public:rw
    working_dir: /srv/agent

  ###> doctrine/doctrine-bundle ###
  database-citoyen:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data-citoyen:/var/lib/postgresql/data:rw

  database-agent:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data-agent:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  redis-citoyen:
    image: redislabs/rejson:latest

volumes:
  citoyen-public:
  agent-public:
  ###> doctrine/doctrine-bundle ###
  db-data-citoyen:
  db-data-agent:
  ###< doctrine/doctrine-bundle ###
