framework:
    cache:
        default_redis_provider: 'redis://:%env(REDIS_PASSWORD)%@%env(REDIS_HOST)%:%env(REDIS_PORT)%'
        app: cache.adapter.redis
        pools:
            referentials.cache:
                adapter: cache.adapter.redis
