framework:
    cache:
        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%'
        
        pools:
            referentials.cache:
                adapter: cache.adapter.redis
