doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            referentials:
                url: '%env(resolve:REFERENTIALS_DATABASE_URL)%'
    orm:
        default_entity_manager: default
        entity_managers:
            auto_generate_proxy_classes: true
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App        
            referentials:
                connection: referentials
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Referentials:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Referential/Entity'
                        prefix: 'App\Referential\Entity'
                        alias: Referentials
                dql:
                    string_functions:
                        unaccent: App\DQL\Unaccent

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod: &prod
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

when@e2e: *prod
