doctrine:
    dbal:
        default_connection: referentials
        connections:
            referentials:
                url: '%env(resolve:REFERENTIALS_DATABASE_URL)%'
    orm:
        default_entity_manager: referentials
        entity_managers:
            auto_generate_proxy_classes: true      
            referentials:
                connection: referentials
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Referentials:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Referential/Entity'
                        prefix: 'App\Referential\Entity'
                        alias: Referentials
                dql:
                    string_functions:
                        unaccent: App\DQL\Unaccent
                        cast: DoctrineExtensions\Query\Mysql\Cast
                    numeric_functions:
                        acos: DoctrineExtensions\Query\Mysql\Acos
                        cos: DoctrineExtensions\Query\Mysql\Cos
                        radians: DoctrineExtensions\Query\Mysql\Radians
                        sin: DoctrineExtensions\Query\Mysql\Sin 

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod: &prod
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            metadata_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
            query_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

when@e2e: *prod
