framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    trusted_proxies: '%env(TRUSTED_PROXIES)%'

    session:
        name: PHPPELSESSID
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

