framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

when@dev:
    framework:
        trusted_proxies: '%env(TRUSTED_PROXIES)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
