monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - oodrive # Logs dedicated to communication with the Oodrive API

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!oodrive"]
                max_files: 20
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!oodrive"]
            oodrive:
                type: rotating_file
                path: "%kernel.logs_dir%/oodrive_%kernel.environment%.log"
                level: debug
                channels: [ "oodrive" ]
                max_files: 20

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod: &prod
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            file_log:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
                channels: ["!oodrive"]
                max_files: 20
            oodrive_log:
                type: rotating_file
                path: "%kernel.logs_dir%/oodrive_%kernel.environment%.log"
                level: error
                channels: [ "oodrive" ]
                max_files: 20
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr

when@e2e: *prod
