vich_uploader:
    db_driver: orm
    storage: flysystem
    metadata:
        type: attribute
    mappings:
        files:
            uri_prefix: /files
            upload_destination: default.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

