apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "pel-chart.fullname" . }}
  labels:
    {{- include "pel-chart.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ include "pel-chart.fullname" . }}-cert
    hosts:
    - {{ .Values.global.domain }}
