---
all:
    hosts:
        demo:
            ansible_connection: ssh
            ansible_host: "{{ vault_server_demo_host }}"
            ansible_user: "{{ vault_server_user }}"
            server_name: "{{ vault_server_demo_name }}"
            server_user: "{{ vault_server_user }}"
            force_reload_db: False
            force_referential_update: True
            in_php_main_machine: True
            in_ipms: False
            CITOYEN_DOMAIN: https://pel-demo-citoyen.forge.smile.fr
 
