---
all:
    hosts:
        php1:
            ansible_connection: ssh
            ansible_host: "{{ vault_pp_php_server_host1 }}"
            ansible_user: "{{ vault_server_user }}"
            server_name: "dapip307php1"
            server_user: "{{ vault_server_ipms_user }}"
            force_reload_db: False
            force_referential_update: True
            ansistrano_git_repo: "{{ vault_git_repo_anfsi }}"

        php2:
            ansible_connection: ssh
            ansible_host: "{{ vault_pp_php_server_host2 }}"
            ansible_user: "{{ vault_server_user }}"
            server_name: "dapip307php2"
            server_user: "{{ vault_server_ipms_user }}"
            force_reload_db: False
            force_referential_update: True
            ansistrano_git_repo: "{{ vault_git_repo_anfsi }}"
        web1:
            ansible_connection: ssh
            ansible_host: "{{ vault_pp_web_server_host1 }}"
            ansible_user: "{{ vault_server_user }}"
            server_name: "dapip307web1"
            server_user: "{{ vault_server_ipms_user }}"
            force_reload_db: False
            force_referential_update: True
            ansistrano_git_repo: "{{ vault_git_repo_anfsi }}"

        web2:
            ansible_connection: ssh
            ansible_host: "{{ vault_pp_web_server_host2 }}"
            ansible_user: "{{ vault_server_user }}"
            server_name: "dapip307web2"
            server_user: "{{ vault_server_ipms_user }}"
            force_reload_db: False
            force_referential_update: True
            ansistrano_git_repo: "{{ vault_git_repo_anfsi }}"
