# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage.aws:
            adapter: 'aws'
            options:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET)%'
                streamReads: true

        default.storage.memory:
            adapter: 'memory'
            
        default.storage.local:
            adapter: 'local'
            options:
                directory: '%env(APP_UPLOADS_SOURCE_DIRECTORY)%'
         
        default.storage:
            adapter: 'lazy'
            options:
                source: '%env(APP_UPLOADS_SOURCE)%'
