# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    #esi: true
    #fragments: true
    php_errors:
        log: true
    session:
        handler_id: '%env(REDIS_URL)%'
        cookie_secure: auto
        cookie_samesite: lax

when@dev:
    framework:
        trusted_proxies: '%env(TRUSTED_PROXIES)%'

when@test:
    framework:
        session:
            handler_id: null
        test: true
