framework:
    http_client:
        scoped_clients:
            oodrive.client:
                scope: 'https://sharing\.oodrive\.com'
                base_uri: '%env(OODRIVE_BASE_URI)%'
                headers:
                    Accept: 'application.json'
                    Content-Type: 'application.json'
            salesforce.client:
                scope: 'https://%env(SALESFORCE_ID_DOMAIN)%\.(rest|auth)\.marketingcloudapis\.com'
                headers:
                    Accept: 'application.json'
                    Content-Type: 'application.json'
