framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            activemq: 
                dsn: '%env(ACTIVEMQ_DSN)%'
                options:
                    queue: '%env(ACTIVEMQ_QUEUE_NAME)%'
            sync: 'sync://'
                
        # https://symfony.com/doc/current/messenger.html#transport-configuration
        # async: '%env(MESSENGER_TRANSPORT_DSN)%'
        # failed: 'doctrine://default?queue_name=failed'
        # sync: 'sync://'

        routing:
        # Route your messages to the transports
        # 'App\Message\YourMessage': async
            'App\Salesforce\Messenger\Appointment\AppointmentMessage': sync
            'App\Salesforce\Messenger\AppointmentInformations\AppointmentInformationsMessage': sync
            'App\Salesforce\Messenger\ComplaintAssignment\ComplaintAssignmentMessage': sync
            'App\Salesforce\Messenger\ComplaintFetch\ComplaintFetchMessage': sync
            'App\Salesforce\Messenger\ComplaintRejection\ComplaintRejectionMessage': sync
            'App\Salesforce\Messenger\ComplaintReportSend\ComplaintReportSendMessage': sync
            'App\Salesforce\Messenger\UnitReassignment\UnitReassignmentMessage': sync
            
            'App\Notification\Messenger\Assignement\AssignementMessage': sync
            'App\Complaint\Messenger\ComplaintFetch\ComplaintFetchMessage': sync
            'App\Notification\Messenger\UnitReassignement\AskUnitReassignementMessage': sync
            'App\Notification\Messenger\UnitReassignement\UnitReassignementMessage': sync
            
            'App\Messenger\InformationCenter\InfocentreMessage': activemq

when@test:
    framework:
        messenger:
            transports:
                activemq: 'in-memory://'
