monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - oodrive # Logs dedicated to communication with the Oodrive API
        - application_traces_gn # Logs dedicated to the application traces for the GN institution
        - application_traces_pn # Logs dedicated to the application traces for the GN institution

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event", "!oodrive", "!application_traces_gn", "!application_traces_pn" ]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console", "!oodrive", "!application_traces_gn", "!application_traces_pn" ]
            oodrive:
                type: stream
                path: "%kernel.logs_dir%/oodrive_%kernel.environment%.log"
                level: debug
                channels: [ "oodrive" ]
            application_traces_gn:
                type: stream
                path: "%kernel.logs_dir%/application_traces_gn_%kernel.environment%.log"
                level: debug
                channels: [ "application_traces_gn" ]
                formatter: 'app.logger.formatter.json_traces'
            application_traces_pn:
                type: stream
                path: "%kernel.logs_dir%/application_traces_pn_%kernel.environment%.log"
                level: debug
                channels: [ "application_traces_pn" ]
                formatter: 'app.logger.formatter.json_traces'


when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            file_log:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
                channels: [ "!oodrive" ]
            oodrive_log:
                type: stream
                path: "%kernel.logs_dir%/oodrive_%kernel.environment%.log"
                level: error
                channels: [ "oodrive" ]
            application_traces_gn_log:
                type: stream
                path: "%kernel.logs_dir%/application_traces_gn_%kernel.environment%.log"
                level: info
                channels: [ "application_traces_gn" ]
                formatter: 'app.logger.formatter.json_traces'
            application_traces_pn_log:
                type: stream
                path: "%kernel.logs_dir%/application_traces_pn_%kernel.environment%.log"
                level: info
                channels: [ "application_traces_pn" ]
                formatter: 'app.logger.formatter.json_traces'
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
