twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['forms/theme.html.twig']
    globals:
        sso_is_enabled: '%sso.enabled%'
        userback_access_token: '%app.userback_access_token%'

when@test:
    twig:
        strict_variables: true
