---
- hosts: all

  become: true

  environment:
    APP_ENV: prod
    ENABLE_SSO: "false"
    FILE_UNITS: service.csv

  vars_files:
    - ../vars/vars.yaml
    - ../vault/vault.yaml

  roles:
    - ansistrano.deploy

