---
- hosts: all

  become: true

  environment:
    APP_ENV: prod
    ENABLE_SSO: "false"
    FILE_UNITS_GN: pwb_ref_unite_gn.csv
    FILE_UNITS_PN: pwb_ref_unite_pn_exp.csv
    OODRIVE_BASE_URI: https://sharing.oodrive.com
    OODRIVE_WORKSPACE: pel
    OODRIVE_OAUTH_CLIENT_ID: pel
    FOLDER_ROTATION_COUNT: 10
    FOLDER_ROTATION_TRESHOLD: 1
    OODRIVE_ROOT_FOLDER_ID: HcxbMKkGLFo
    OODRIVE_FETCHED_FOLDER_ID: a6mxUkP9a9A
    OODRIVE_TMP_COMPLAINT_FOLDER: HcxbMKkGLFo
    OODRIVE_REPORT_FOLDER: PV
    OODRIVE_COMPLAINT_FILENAME: plainte.json
    ACTIVEMQ_DSN: stomp://localhost:61613
    ACTIVEMQ_QUEUE_NAME: /queue/pel
    
  vars_files:
    - ../vars/vars.yaml
    - ../vault/vault.yaml

  roles:
    - ansistrano.deploy

