---
- hosts: all

  become: true

  environment:
    APP_ENV: prod
    ENABLE_SSO: "false"
    FILE_UNITS_GN: pwb_ref_unite_gn.csv
    FILE_UNITS_PN: pwb_ref_unite_pn_exp.csv
    OODRIVE_BASE_URI: https://snc28pp.snc.oodrive.com
    OODRIVE_WORKSPACE: pel-developpement
    OODRIVE_OAUTH_CLIENT_ID: pel-developpement
    FOLDER_ROTATION_COUNT: 10
    FOLDER_ROTATION_TRESHOLD: 100
    OODRIVE_ROOT_FOLDER_ID: PPcL4nnuFDQ
    OODRIVE_FETCHED_FOLDER_ID: nfbHizvti4A
    OODRIVE_TMP_COMPLAINT_FOLDER: PPcL4nnuFDQ
    OODRIVE_REPORT_FOLDER: PV
    OODRIVE_COMPLAINT_FILENAME: plainte.json
    ACTIVEMQ_DSN: stomp://localhost:61613
    ACTIVEMQ_QUEUE_NAME: /queue/pel
    SALESFORCE_RECIPIENT: pel.sensiolabs@gmail.com
    AWS_S3_ENDPOINT: http://localhost:9000
    AWS_S3_BUCKET: pel-bucket
    AWS_S3_REGION: eu-west-3
    
  vars_files:
    - ../vars/vars.yaml
    - ../vault/vault.yaml

  roles:
    - ansistrano.deploy

