---
- hosts: all

  become: true

  environment:
    APP_ENV: prod
    APP_SECRET: "{{ vault_symfony_secret }}"
    DATABASE_URL: "{{ vault_database_url }}"
    TRUSTED_PROXIES: "{{ vault_trusted_proxies }}"
    REDIS_HOST: 127.0.0.1

  vars_files:
    - ../vars/vars.yaml
    - ../vault/vault.yaml

  roles:
    - ansistrano.deploy

