<?php

namespace App\Referential\DataFixtures;

use App\Referential\Entity\Country;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Bundle\FixturesBundle\FixtureGroupInterface;
use Doctrine\Persistence\ObjectManager;

class CountriesFixtures extends Fixture implements FixtureGroupInterface
{
    public static function getGroups(): array
    {
        return ['referentials'];
    }

    public function load(ObjectManager $manager): void
    {
        $countries = [
            new Country('AF', 'Afghanistan', 99212),
            new Country('ZA', 'Afrique du sud', 99303),
            new Country('AL', 'Albanie', 99125),
            new Country('DZ', 'Algérie', 99352),
            new Country('DE', 'Allemagne', 99109),
            new Country('AD', 'Andorre', 99130),
            new Country('AO', 'Angola', 99395),
            new Country('AG', 'Antigua et barbuda', 99441),
            new Country('SA', 'Arabie saoudite', 99201),
            new Country('AR', 'Argentine', 99415),
            new Country('AM', 'Arménie', 99252),
            new Country('AU', 'Australie', 99501),
            new Country('AT', 'Autriche', 99110),
            new Country('AZ', 'Azerbaïdjan', 99253),
            new Country('BS', 'Bahamas', 99436),
            new Country('BH', 'Bahreïn', 99249),
            new Country('BD', 'Bangladesh', 99246),
            new Country('BB', 'Barbade', 99434),
            new Country('BE', 'Belgique', 99131),
            new Country('BZ', 'Belize', 99429),
            new Country('BJ', 'Bénin', 99327),
            new Country('BT', 'Bhoutan', 99214),
            new Country('BY', 'Biélorussie', 99148),
            new Country('MM', 'Birmanie', 99224),
            new Country('BO', 'Bolivie', 99418),
            new Country('BQ', 'Bonaire Saint-Eustache et saba', 99443),
            new Country('BA', 'Bosnie-Herzégovine', 99118),
            new Country('BW', 'Botswana', 99347),
            new Country('BR', 'Brésil', 99416),
            new Country('BN', 'Brunei Darussalam', 99225),
            new Country('BG', 'Bulgarie', 99111),
            new Country('BF', 'Burkina faso', 99331),
            new Country('BI', 'Burundi', 99321),
            new Country('KH', 'Cambodge', 99234),
            new Country('CM', 'Cameroun', 99322),
            new Country('CA', 'Canada', 99401),
            new Country('CV', 'Cap-Vert', 99396),
            new Country('CL', 'Chili', 99417),
            new Country('CN', 'Chine', 99216),
            new Country('CY', 'Chypre', 99254),
            new Country('CO', 'Colombie', 99419),
            new Country('KM', 'Comores', 99397),
            new Country('CG', 'Congo', 99324),
            new Country('KP', 'Corée du nord', 99238),
            new Country('KR', 'Corée du sud', 99239),
            new Country('CR', 'Costa rica', 99406),
            new Country('CI', 'Côte-d\'ivoire', 99326),
            new Country('HR', 'Croatie', 99119),
            new Country('CU', 'Cuba', 99407),
            new Country('CW', 'Curacao', 99444),
            new Country('DK', 'Danemark', 99101),
            new Country('DJ', 'Djibouti', 99399),
            new Country('DM', 'Dominique', 99438),
            new Country('EG', 'Egypte', 99301),
            new Country('SV', 'El Salvador', 99414),
            new Country('AE', 'Emirats arabes unis', 99247),
            new Country('EC', 'Equateur', 99420),
            new Country('ER', 'Erythrée', 99317),
            new Country('ES', 'Espagne', 99134),
            new Country('EE', 'Estonie', 99106),
            new Country('US', 'Etats - unis', 99404),
            new Country('ET', 'Ethiopie', 99315),
            new Country('FJ', 'Fidji', 99508),
            new Country('FI', 'Finlande', 99105),
            new Country('FR', 'France', 99100),
            new Country('GA', 'Gabon', 99328),
            new Country('GM', 'Gambie', 99304),
            new Country('GE', 'Géorgie', 99255),
            new Country('GH', 'Ghana', 99329),
            new Country('GR', 'Gréce', 99126),
            new Country('GD', 'Grenade', 99435),
            new Country('GT', 'Guatemala', 99409),
            new Country('GN', 'Guinée', 99330),
            new Country('GW', 'Guinée - bissau', 99392),
            new Country('GQ', 'Guinée - equatoriale', 99314),
            new Country('GY', 'Guyana', 99428),
            new Country('HT', 'Haïti', 99410),
            new Country('HN', 'Honduras', 99411),
            new Country('HU', 'Hongrie', 99112),
            new Country('MH', 'Iles marshall', 99515),
            new Country('MU', 'Iles maurice', 99390),
            new Country('SB', 'Iles salomon', 99512),
            new Country('IN', 'Inde', 99223),
            new Country('ID', 'Indonésie', 99231),
            new Country('IQ', 'Iraq', 99203),
            new Country('IR', 'Iran', 99204),
            new Country('IE', 'Irlande', 99136),
            new Country('IS', 'Islande', 99102),
            new Country('IL', 'Israël', 99207),
            new Country('IT', 'Italie', 99127),
            new Country('JM', 'Jamaïque', 99426),
            new Country('JP', 'Japon', 99217),
            new Country('JO', 'Jordanie', 99222),
            new Country('KZ', 'Kazakhstan', 99256),
            new Country('KE', 'Kenya', 99332),
            new Country('KG', 'Kirghizistan', 99257),
            new Country('KI', 'Kiribati', 99513),
            new Country('RS', 'Kosovo', 99157),
            new Country('KW', 'Koweït', 99240),
            new Country('LA', 'Laos', 99241),
            new Country('LS', 'Lesotho', 99348),
            new Country('LV', 'Lettonie', 99107),
            new Country('LB', 'Liban', 99205),
            new Country('LR', 'Liberia', 99302),
            new Country('LY', 'Libye', 99316),
            new Country('LI', 'Liechtenstein', 99113),
            new Country('LT', 'Lituanie', 99108),
            new Country('LU', 'Luxembourg', 99137),
            new Country('MK', 'Macédoine', 99156),
            new Country('MG', 'Madagascar', 99333),
            new Country('MY', 'Malaisie', 99227),
            new Country('MW', 'Malawi', 99334),
            new Country('MV', 'Maldives', 99229),
            new Country('ML', 'Mali', 99335),
            new Country('MT', 'Malte et gozo', 99144),
            new Country('MA', 'Maroc', 99350),
            new Country('MR', 'Mauritanie', 99336),
            new Country('MX', 'Mexique', 99405),
            new Country('FM', 'Micronésie', 99516),
            new Country('MD', 'Moldavie', 99151),
            new Country('MC', 'Monaco', 99138),
            new Country('MN', 'Mongolie', 99242),
            new Country('ME', 'Monténégro', 99120),
            new Country('MZ', 'Mozambique', 99393),
            new Country('NA', 'Namibie', 99311),
            new Country('NR', 'Nauru', 99507),
            new Country('NP', 'Népal', 99215),
            new Country('NI', 'Nicaragua', 99412),
            new Country('NE', 'Niger', 99337),
            new Country('NG', 'Nigeria', 99338),
            new Country('NU', 'Norvège', 99103),
            new Country('NZ', 'Nouvelle - zélande', 99502),
            new Country('OM', 'Oman', 99250),
            new Country('UG', 'Ouganda', 99339),
            new Country('UZ', 'Ouzbékistan', 99258),
            new Country('PK', 'Pakistan', 99213),
            new Country('PW', 'Palaos', 99517),
            new Country('PS', 'Palestine', 99261),
            new Country('PA', 'Panama', 99413),
            new Country('PG', 'Papouasie - nouvelle - guinée', 99510),
            new Country('PY', 'Paraguay', 99421),
            new Country('NL', 'Pays - bas', 99135),
            new Country('PE', 'Pérou', 99422),
            new Country('PH', 'Philippines', 99220),
            new Country('PL', 'Pologne', 99122),
            new Country('PT', 'Portugal', 99139),
            new Country('QA', 'Qatar', 99248),
            new Country('CF', 'République centrafricaine', 99323),
            new Country('CD', 'République démocratique congo', 99312),
            new Country('DO', 'République dominicaine', 99408),
            new Country('CZ', 'République tchéque', 99116),
            new Country('RO', 'Roumanie', 99114),
            new Country('GB', 'Royaume - uni', 99132),
            new Country('RU', 'Russie', 99123),
            new Country('RW', 'Rwanda', 99340),
            new Country('KN', 'Saint - Christophe et Niévès', 99442),
            new Country('SM', 'Saint - marin', 99128),
            new Country('SX', 'Saint - martin', 99445),
            new Country('VC', 'Saint - vincent et les grenadines', 99440),
            new Country('LC', 'Sainte - lucie', 99439),
            new Country('WS', 'Samoa', 99506),
            new Country('ST', 'São Tomé et Príncipe', 99394),
            new Country('SN', 'Sénégal', 99341),
            new Country('RS', 'Serbie', 99121),
            new Country('SC', 'Seychelles', 99398),
            new Country('SL', 'Sierra leone', 99342),
            new Country('SG', 'Singapour', 99226),
            new Country('SK', 'Slovaquie', 99117),
            new Country('SI', 'Slovénie', 99145),
            new Country('SO', 'Somalie', 99318),
            new Country('SD', 'Soudan', 99343),
            new Country('SS', 'Soudan du sud', 99349),
            new Country('LK', 'Sri lanka', 99235),
            new Country('SE', 'Suède', 99104),
            new Country('CH', 'Suisse', 99140),
            new Country('SR', 'Suriname', 99437),
            new Country('SZ', 'Swaziland', 99391),
            new Country('SY', 'Syrie', 99206),
            new Country('TJ', 'Tadjikistan', 99259),
            new Country('TW', 'Taiwan', 99236),
            new Country('TZ', 'Tanzanie', 99309),
            new Country('TD', 'Tchad', 99344),
            new Country('TH', 'Thaïlande', 99219),
            new Country('TL', 'Timor - Oriental', 99262),
            new Country('TG', 'Togo', 99345),
            new Country('TO', 'Tonga', 99509),
            new Country('TT', 'Trinité - et - tobago', 99433),
            new Country('TN', 'Tunisie', 99351),
            new Country('TM', 'Turkménistan', 99260),
            new Country('TR', 'Turquie', 99208),
            new Country('TV', 'Tuvalu', 99511),
            new Country('UA', 'Ukraine', 99155),
            new Country('UY', 'Uruguay', 99423),
            new Country('VU', 'Vanuatu', 99514),
            new Country('VA', 'Vatican', 99129),
            new Country('VE', 'Venezuela', 99424),
            new Country('VN', 'Viêt Nam', 99243),
            new Country('YE', 'Yémen', 99251),
            new Country('ZM', 'Zambie', 99346),
            new Country('ZW', 'Zimbabwe', 99310),
        ];

        foreach ($countries as $country) {
            $manager->persist($country);
        }

        $manager->flush();
    }
}
