parameters:
    app.france_code: 99100
    app.file_cities: '%env(FILE_CITIES)%'
    app.referentials_base_path: '%kernel.project_dir%/referentials'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $franceCode: '%app.france_code%'
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  Redis:
    class: Redis
    calls:
      - connect:
          - '%env(REDIS_HOST)%'
          - '%env(int:REDIS_PORT)%'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@Redis'

  Symfony\Component\EventDispatcher\EventSubscriberInterface $addAddressSubscriber: '@App\Form\EventListener\AddAddressSubscriber'
  Symfony\Component\EventDispatcher\EventSubscriberInterface $addAddressCountrySubscriber: '@App\Form\EventListener\AddAddressCountrySubscriber'
  
  App\Security\FranceConnectListener:
      $baseUri: '%env(FRANCE_CONNECT_BASE_URI)%'
      $logoutTargetPathMap: ~  # Replaced in LogoutTargetPass
      
  # Referentials
  
  App\Referential\DataFixtures\City\CityFileFixtures:
    arguments:
      $citiesFixturesPath: '%app.referentials_base_path%/%app.file_cities%'
  
  App\Referential\Provider\Country\CountryProviderInterface: '@App\Referential\Provider\Country\DatabaseCountryProvider'
