parameters:
    app.france_code: 99160
    app.france_connect_code: 99100
    app.french_nationality_code: '23'
    app.file_cities: '%env(FILE_CITIES)%'
    app.file_jobs_male: '%env(FILE_JOBS_MALE)%'
    app.file_jobs_female: '%env(FILE_JOBS_FEMALE)%'
    app.file_cities_services: '%env(FILE_CITIES_SERVICES)%'
    app.file_cities_units: '%env(FILE_CITIES_UNITS)%'
    app.file_units_gn: '%env(FILE_UNITS_GN)%'
    app.file_units_pn: '%env(FILE_UNITS_PN)%'
    app.file_departments: '%env(FILE_DEPARTMENTS)%'
    app.file_countries: '%env(FILE_COUNTRIES)%'
    app.file_nationalities: '%env(FILE_NATIONALITIES)%'
    app.referentials_base_path: '%kernel.project_dir%/referentials'
    app.jedonnemonavis_id: '%env(JEDONNEMONAVIS_ID)%'
    app.jedonnemonavis_key: '%env(JEDONNEMONAVIS_KEY)%'
    app.file_services: '%env(FILE_SERVICES)%'
    app.folder_rotation.count: '%env(FOLDER_ROTATION_COUNT)%'
    app.folder_rotation.treshold: '%env(FOLDER_ROTATION_TRESHOLD)%'
    app.oodrive.root_folder_id: '%env(OODRIVE_ROOT_FOLDER_ID)%'
    app.google_maps_api_key: '%env(GOOGLE_MAPS_API_KEY)%'
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $franceCode: '%app.france_code%'
            $franceConnectCode: '%app.france_connect_code%'
            $frenchNationalityCode: '%app.french_nationality_code%'
            $folderRotationCount: '%app.folder_rotation.count%'
            $folderRotationTreshold: '%app.folder_rotation.treshold%'
            $oodriveRootFolderId: '%app.oodrive.root_folder_id%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    Redis:
        class: Redis
        calls:
            -   connect:
                    - '%env(REDIS_HOST)%'
                    - '%env(int:REDIS_PORT)%'
    
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'
    
    Symfony\Component\EventDispatcher\EventSubscriberInterface $addAddressSubscriber: '@App\Form\EventListener\AddAddressSubscriber'
    
    App\Etalab\EtalabApiClientInterface: '@App\Etalab\EtalabAddressApiClient'
    App\Oodrive\ApiClientInterface: '@App\Oodrive\ApiClient'
    
    App\Security\FranceConnectListener:
        $baseUri: '%env(FRANCE_CONNECT_BASE_URI)%'
        $logoutTargetPathMap: ~  # Replaced in LogoutTargetPass
    
    # Referentials
    
    App\Referential\DataFixtures\City\CityFileFixtures:
        arguments:
            $citiesFixturesPath: '%app.referentials_base_path%/%app.file_cities%'
            
    App\Referential\DataFixtures\Country\CountryFileFixtures:
        arguments:
            $countryFixturesPath: '%app.referentials_base_path%/%app.file_countries%'
    
    App\Referential\DataFixtures\Department\DepartmentFileFixtures:
        arguments:
            $departmentsFixturesPath: '%app.referentials_base_path%/%app.file_departments%'
    
    App\Referential\DataFixtures\Job\JobMaleFileFixtures:
        arguments:
            $jobsFixturesPath: '%app.referentials_base_path%/%app.file_jobs_male%'
    
    App\Referential\DataFixtures\Job\JobFemaleFileFixtures:
        arguments:
            $jobsFixturesPath: '%app.referentials_base_path%/%app.file_jobs_female%'
    
    App\Referential\DataFixtures\CityService\CityServiceFileFixtures:
        arguments:
            $citiesServicesFixturesPath: '%app.referentials_base_path%/%app.file_cities_services%'
    
    App\Referential\DataFixtures\Service\ServiceFileFixtures:
        arguments:
            $servicesFixturesPath: '%app.referentials_base_path%/%app.file_services%'
    
    App\Referential\DataFixtures\Unit\UnitGNFileFixtures:
        arguments:
            $unitsGNFixturesPath: '%app.referentials_base_path%/%app.file_units_gn%'

    App\Referential\DataFixtures\Unit\UnitPNFileFixtures:
        arguments:
            $unitsPNFixturesPath: '%app.referentials_base_path%/%app.file_units_pn%'

    App\Referential\DataFixtures\CityUnit\CityUnitFileFixtures:
        arguments:
            $citiesUnitsFixturesPath: '%app.referentials_base_path%/%app.file_cities_units%'

    App\Referential\DataFixtures\Nationality\NationalityFileFixtures:
        arguments:
            $nationalitiesFixturesPath: '%app.referentials_base_path%/%app.file_nationalities%'

    App\Referential\Provider\Country\CountryProviderInterface: '@App\Referential\Provider\Country\DatabaseCountryProvider'
    
    App\Referential\Provider\Nationality\NationalityProviderInterface: '@App\Referential\Provider\Nationality\DatabaseNationalityProvider'

    libphonenumber\PhoneNumberUtil:
        factory: [ 'libphonenumber\PhoneNumberUtil', 'getInstance' ]

    # Oodrive HTTP Client Oauth management service
    App\Oodrive\OAuth2\GrantType\AuthorizationCodeGrantType:
        arguments:
            $tokenUrl: '%env(OODRIVE_BASE_URI)%/auth/oauth/token'
            $workspace: '%env(OODRIVE_WORKSPACE)%'
            $clientId: '%env(OODRIVE_OAUTH_CLIENT_ID)%'
            $clientSecret: '%env(OODRIVE_OAUTH_CLIENT_SECRET)%'
            $username: '%env(OODRIVE_USERNAME)%'
            $password: '%env(OODRIVE_PASSWORD)%'
    
