imports:
    - { resource: services_test_common.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Etalab\EtalabApiClientInterface: '@App\Tests\Behat\MockedClasses\EtalabApiClient'
