services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Factory\:
        resource: '../tests/Factory/*'
        
    Symfony\Component\HttpFoundation\Session\SessionFactoryInterface: '@session.factory'

    Psr\Container\ContainerInterface $behatDriverContainer: '@behat.driver.service_container'
    App\Oodrive\ApiClientInterface: '@App\Tests\Behat\MockedClasses\FakeOodriveApiClient'
    App\Oodrive\ReportsFetcher\ReportsFetcherInterface: '@App\Tests\Behat\MockedClasses\FakeReportFetcher'

    App\Tests\Behat\FranceConnectContext:
        $baseUri: '%env(FRANCE_CONNECT_BASE_URI)%'

    App\Tests\Doubles\FranceConnectClientFake:
        decorates: 'knpu.oauth2.client.france_connect'
        arguments:
            $clientId: '%env(FRANCE_CONNECT_CLIENT_ID)%'
            $baseUri: '%env(FRANCE_CONNECT_BASE_URI)%'

    App\Tests\Doubles\FranceConnectGuzzleClientFake:
        $clientId: '%env(FRANCE_CONNECT_CLIENT_ID)%'
        $clientSecret: '%env(FRANCE_CONNECT_CLIENT_SECRET)%'
        $baseUri: '%env(FRANCE_CONNECT_BASE_URI)%'

    App\Generator\Complaint\ComplaintVaultGeneratorJson:
        public: true

    App\Tests\Factory\ComplaintFactory:
        public: true
