parameters:
    app.france_code: 'FR'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $franceCode: '%app.france_code%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Thesaurus\TownAndDepartmentThesaurusProviderInterface $townAndDepartmentAndDepartmentThesaurusProvider: '@App\Thesaurus\MockedTownAndDepartmentAndDepartmentThesaurusProvider'

    Symfony\Component\EventDispatcher\EventSubscriberInterface $addAddressSubscriber: '@App\Form\EventListener\AddAddressSubscriber'
