parameters:
  app.france_code: 'FR'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $franceCode: '%app.france_code%'
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  Redis:
    class: Redis
    calls:
      - connect:
          - '%env(REDIS_HOST)%'
          - '%env(int:REDIS_PORT)%'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@Redis'

  Symfony\Component\EventDispatcher\EventSubscriberInterface $addAddressSubscriber: '@App\Form\EventListener\AddAddressSubscriber'
  Symfony\Component\EventDispatcher\EventSubscriberInterface $addAddressCountrySubscriber: '@App\Form\EventListener\AddAddressCountrySubscriber'

  Symfony\Component\Form\DataTransformerInterface $townToTownAndDepartmentTransformer: '@App\Form\DataTransformer\TownToTownAndDepartmentTransformer'
  
  App\Security\FranceConnectListener:
      $baseUri: '%env(FRANCE_CONNECT_BASE_URI)%'
      $logoutTargetPathMap: ~  # Replaced in LogoutTargetPass
