---
- hosts: all

  become: true

  environment:
    APP_ENV: prod
    REDIS_HOST: 127.0.0.1
    FILE_CITIES: insee_commune.csv
    FILE_COUNTRIES: insee_pays.csv
    FILE_DEPARTMENTS: departement_2022.csv
    FILE_JOBS: table_de_conversion_professions[11028].csv
    FILE_CITIES_SERVICES: competence_securite_publique.csv
    FILE_CITIES_UNITS: pwb_ref_insee_unite.csv
    FILE_UNITS_GN: pwb_ref_unite_gn.csv
    FILE_UNITS_PN: pwb_ref_unite_pn_exp.csv
    FILE_NATIONALITIES: Nationalites.csv
    FILE_NATURE_PLACES: natures_de_lieux.csv
    FILE_DOCUMENT_TYPES: Ref_derive_docs_officiels.csv
    FILE_PAYMENT_CATEGORIES: nature_moyen_paiement.csv
    OODRIVE_BASE_URI: https://snc28pp.snc.oodrive.com
    OODRIVE_WORKSPACE: pel-developpement
    OODRIVE_OAUTH_CLIENT_ID: pel-developpement
    FOLDER_ROTATION_COUNT: 10
    FOLDER_ROTATION_TRESHOLD: 100
    OODRIVE_ROOT_FOLDER_ID: PPcL4nnuFDQ
    OODRIVE_FETCHED_FOLDER_ID: nfbHizvti4A
    OODRIVE_FETCHED_ZIP_NAME: PV.zip
    OODRIVE_REPORT_FOLDER: PV
    GOOGLE_MAPS_API_KEY: AIzaSyC0UUADE5DrNeRMqd3Dp0MMuiMSTWrI12I
    ACCES_LIBRE_API_BASE_URI: https://acceslibre.beta.gouv.fr/api/erps/
    ACCES_LIBRE_API_KEY: vYtCZqo4.fbVMB3TsQQ6Bti6L2DdCcryt5ohTbtQM
    WKHTMLTOPDF_PATH: /usr/local/bin/wkhtmltopdf
    
  vars_files:
    - ../vars/vars.yaml
    - ../vault/vault.yaml

  roles:
    - ansistrano.deploy

