---
- hosts: all

  become: true

  environment:
    APP_ENV: prod
    APP_SECRET: "{{ vault_symfony_secret }}"
    DATABASE_URL: "{{ vault_database_url }}"
    TRUSTED_PROXIES: "{{ vault_trusted_proxies }}"
    REDIS_HOST: 127.0.0.1
    FRANCE_CONNECT_CLIENT_ID: "{{ vault_france_connect_client_id }}"
    FRANCE_CONNECT_CLIENT_SECRET: "{{ vault_france_connect_client_secret }}"
    FRANCE_CONNECT_BASE_URI: "{{ vault_france_connect_base_uri }}"

  vars_files:
    - ../vars/vars.yaml
    - ../vault/vault.yaml

  roles:
    - ansistrano.deploy

