---
- hosts: all

  become: true

  environment:
    APP_ENV: prod
    REDIS_HOST: 127.0.0.1
    FILE_CITIES: insee_commune.csv
    FILE_COUNTRIES: insee_pays.csv
    FILE_DEPARTMENTS: departement_2022.csv
    FILE_JOBS_MALE: Liste_libelles_professions_hommes_2023.csv
    FILE_JOBS_FEMALE: Liste_libelles_professions_femmes_2023.csv
    FILE_SERVICES: service.csv
    FILE_CITIES_SERVICES: competence_securite_publique.csv
    FILE_CITIES_UNITS: pwb_ref_insee_unite.csv
    FILE_UNITS_GN: pwb_ref_unite_gn.csv
    FILE_NATIONALITIES: Nationalites.csv
    OODRIVE_BASE_URI: https://sharing.oodrive.com
    OODRIVE_WORKSPACE: pel
    OODRIVE_OAUTH_CLIENT_ID: pel
    FOLDER_ROTATION_COUNT: 10
    FOLDER_ROTATION_TRESHOLD: 1
    OODRIVE_ROOT_FOLDER_ID: HcxbMKkGLFo
    GOOGLE_MAPS_API_KEY: AIzaSyC0UUADE5DrNeRMqd3Dp0MMuiMSTWrI12I

  vars_files:
    - ../vars/vars.yaml
    - ../vault/vault.yaml

  roles:
    - ansistrano.deploy

